name: "Release .unitypackage ðŸš€"

on:
  push:
    tags:
      - v\d+\.\d+\.\d+
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository ðŸ“¥
        uses: actions/checkout@v4

      - id: get_version
        uses: jannemattila/get-version-from-tag@v3

      - name: Create .unitypackage from Assets ðŸ“¦
        uses: natsuneko-laboratory/create-unitypackage@v3
        with:
          files-glob: |
            ./Assets/Nestor/**
          dest: CopyBlendShape_v${{ steps.get_version.outputs.version }}.unitypackage

      - name: Upload unitypackage artifact ðŸ“¤
        uses: actions/upload-artifact@v3
        with:
          name: CopyBlendShape_v${{ steps.get_version.outputs.version }}.unitypackage
          path: CopyBlendShape_v${{ steps.get_version.outputs.version }}.unitypackage

      - name: Create GitHub release ðŸŽ‰
        uses: ncipollo/release-action@v1
        with:
          artifacts: CopyBlendShape_v${{ steps.get_version.outputs.version }}.unitypackage
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: "Release: ${{ github.ref_name }} ðŸŽŠ"
          draft: false
          prerelease: false
